/*
 * This source file was generated by the Gradle 'init' task
 */
package pruebagradle;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Arrays;


public class AppTest {

    private final App app = new App();

    @Test
    void testVoraz1OrdenBasico() {
        int[][] finca = {
            {0, 2, 10},
            {1, 1, 5},
            {2, 3, 15}
        };

        int[] resultado = app.programacionVoraz1(finca);
        assertEquals(3, resultado.length);
        assertTrue(Arrays.stream(resultado).distinct().count() == 3);
    }

    @Test
    void testVoraz2OrdenBasico() {
        int[][] finca = {
            {0, 2, 10},
            {1, 1, 5},
            {2, 3, 15}
        };

        int[] resultado = app.programacionVoraz2(finca);
        assertEquals(3, resultado.length);
        assertTrue(Arrays.stream(resultado).distinct().count() == 3);
    }

    @Test
    void testFuerzaBrutaResultadoValido() {
        int[][] finca = {
            {0, 2, 10},
            {1, 1, 5},
            {2, 3, 15}
        };

        int[] resultado = app.programacionFuerzaBruta(finca);
        assertEquals(3, resultado.length);
        assertTrue(Arrays.stream(resultado).distinct().count() == 3);
    }

    @Test
    void testCostoDeterminista() {
        int[][] finca = {
            {0, 2, 10},
            {1, 1, 5}
        };

        long costo1 = app.calcularCosto(finca, new int[]{0, 1});
        long costo2 = app.calcularCosto(finca, new int[]{0, 1});
        assertEquals(costo1, costo2);
    }


    @Test
    void testLeerFincaDesdeRecursosArchivoInexistente() {
        int[][] finca = App.leerFincaDesdeRecursos("no_existe.txt");
        assertEquals(0, finca.length);
    }

    @Test
    void testCalcularCostoSinPenalizacion() {
        int[][] finca = {
            {0, 1, 10},
            {1, 1, 5}
        };
        int[] orden = {0, 1};
        long costo = app.calcularCosto(finca, orden);
        assertTrue(costo >= 0);
    }


    @Test
    void testCalcularCostoConPenalizacion() {
        int[][] finca = {
            {0, 1, 10},
            {0, 2, 5}
        };
        int[] orden = {1, 0};
        long costo = app.calcularCosto(finca, orden);
        assertTrue(costo > 0);
    }

    @Test
    void testProgramacionVoraz1ConValoresAleatorios() {
        int[][] finca = {
            {2, 5, 20},
            {3, 1, 10},
            {4, 2, 5},
            {1, 3, 15}
        };
        int[] resultado = app.programacionVoraz1(finca);
        assertEquals(finca.length, resultado.length);
    }

    @Test
    void testProgramacionVoraz2EvitaDivisionPorCero() {
        int[][] finca = {
            {2, 2, 10},
            {3, 1, 5}
        };
        int[] resultado = app.programacionVoraz2(finca);
        assertEquals(2, resultado.length);
    }

    @Test
    void testGetGreeting() {
        String saludo = app.getGreeting();
        assertEquals("Hello World!", saludo);
    }
}
